import { pgTable, varchar, text, timestamp, integer, boolean, bigint, pgEnum } from "drizzle-orm/pg-core";
import { sql, relations } from "drizzle-orm";
import { users } from "./users";
import { projects } from "./projects";

// ============ ENUMS ============

export const mediaSourceTypeEnum = pgEnum("media_source_type", [
    "generated",  // File dibuat oleh AI generation
    "linked",     // User insert via Google Drive URL
    "replaced"    // User replace file yang hilang
]);

export const mediaTypeEnum = pgEnum("media_type", [
    "image",
    "video"
]);

export const entityTypeEnum = pgEnum("entity_type", [
    "character",
    "moodboard",
    "animation",
    "reference"  // General reference image
]);

// ============ USER GOOGLE DRIVE TOKENS ============

export const userGoogleDriveTokens = pgTable("user_google_drive_tokens", {
    id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
    userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: "cascade" }).unique(),

    // OAuth Tokens (should be encrypted in production)
    accessToken: text("access_token").notNull(),
    refreshToken: text("refresh_token").notNull(),
    tokenExpiresAt: timestamp("token_expires_at", { withTimezone: true }).notNull(),

    // User's Drive Info
    driveEmail: varchar("drive_email", { length: 255 }),
    driveFolderId: varchar("drive_folder_id", { length: 255 }), // Root folder for app files
    storageUsedBytes: bigint("storage_used_bytes", { mode: "number" }).default(0),
    storageQuotaBytes: bigint("storage_quota_bytes", { mode: "number" }).default(0),

    // Metadata
    isActive: boolean("is_active").default(true),
    connectedAt: timestamp("connected_at", { withTimezone: true }).defaultNow().notNull(),
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// ============ GENERATED MEDIA ============

export const generatedMedia = pgTable("generated_media", {
    id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
    userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: varchar("project_id", { length: 36 }).references(() => projects.id, { onDelete: "set null" }),

    // Source Entity (character, moodboard, scene, animation)
    entityType: entityTypeEnum("entity_type").notNull(),
    entityId: varchar("entity_id", { length: 36 }).notNull(),

    // Media Info
    mediaType: mediaTypeEnum("media_type").notNull(),
    fileName: varchar("file_name", { length: 255 }).notNull(),
    mimeType: varchar("mime_type", { length: 100 }),
    fileSizeBytes: bigint("file_size_bytes", { mode: "number" }),

    // Source Type (generated by AI or manually linked)
    sourceType: mediaSourceTypeEnum("source_type").default("generated").notNull(),

    // Google Drive Storage
    driveFileId: varchar("drive_file_id", { length: 255 }),
    driveWebViewLink: text("drive_web_view_link"),

    // ========== GENERATED URLS ==========
    // Dari 1 URL input, generate 3 URLs:
    downloadUrl: text("download_url"),        // Untuk AI download (export=download)
    thumbnailUrl: text("thumbnail_url"),      // Untuk preview/gallery (thumbnail)
    publicUrl: text("public_url"),            // Untuk view full (export=view)

    // Manual Link Info (jika user insert via URL)
    originalDriveUrl: text("original_drive_url"),
    linkedAt: timestamp("linked_at", { withTimezone: true }),

    // Generation Info (null jika manual link)
    modelUsed: varchar("model_used", { length: 100 }),
    promptUsed: text("prompt_used"),
    creditsUsed: integer("credits_used").default(0),

    // ========== VERSION CONTROL ==========
    // Variant type: default, expression, pose, style
    variantType: varchar("variant_type", { length: 50 }).default("default"),
    // Variant name for expressions/poses: Happy, Sad, Portrait, Full Body
    variantName: varchar("variant_name", { length: 100 }),
    // Art style used: realistic, anime, ghibli, disney, etc.
    styleUsed: varchar("style_used", { length: 100 }).default("realistic"),
    // Auto-increment version per entity+style
    generationVersion: integer("generation_version").default(1),
    // User-defined version name (editable): "Battle Armor Look", "Main v2"
    versionName: varchar("version_name", { length: 255 }),
    // Primary for this specific style
    isPrimaryForStyle: boolean("is_primary_for_style").default(false),

    // Status
    isAccessible: boolean("is_accessible").default(true),
    isPrimary: boolean("is_primary").default(false), // Primary image for entity (overall)
    lastCheckedAt: timestamp("last_checked_at", { withTimezone: true }),

    // Timestamps
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// ============ RELATIONS ============

export const userGoogleDriveTokensRelations = relations(userGoogleDriveTokens, ({ one }) => ({
    user: one(users, {
        fields: [userGoogleDriveTokens.userId],
        references: [users.id]
    })
}));

export const generatedMediaRelations = relations(generatedMedia, ({ one }) => ({
    user: one(users, {
        fields: [generatedMedia.userId],
        references: [users.id]
    }),
    project: one(projects, {
        fields: [generatedMedia.projectId],
        references: [projects.id]
    })
}));

// ============ TYPES ============

export type UserGoogleDriveToken = typeof userGoogleDriveTokens.$inferSelect;
export type NewUserGoogleDriveToken = typeof userGoogleDriveTokens.$inferInsert;

export type GeneratedMedia = typeof generatedMedia.$inferSelect;
export type NewGeneratedMedia = typeof generatedMedia.$inferInsert;
